### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by MarceloAlves** [MarceloAlves/CVG-Live#1]
- [ ] Add Twitter feed. Pull favorites from Twitter account.
- [ ] Add video feed. Twitch video feed.
- [x] Redesign with new logo.
- [ ] Link to full size bracket.
